title: example
languageCode: "en-us"
pygmentsCodeFences: true
paginate: 1024
theme: "balmy"

disableKinds:
- sitemap

taxonomies:
  release: releases

mediaTypes:
  application/yaml:
    suffixes: ["yml"]

outputFormats:
  YAML:
    mediaType: "application/yaml"
    isPlainText: true

outputs:
  page:
  - HTML
  - JSON
  - YAML

params:
  ThemeShowToC: true
  ThemeIncludeMenu: "/docs/latest/_menu"
  ThemeNavItems: []
  ThemeNavBadges: []

  ShowContributeLinks: true
  RequireContributeLinkMap: false

  CopyrightNotice: ""
  GitRepo: https://github.com/dpb587/bosh-release-site
  GitEditPath: blob/master
  GitCommitPath: commit

  boshReleaseName: caddy
  boshReleaseVersion: ""
