languageCode: "en-us"
paginate: 32
theme: "book-fork"
# googleAnalytics: "UA-37464314-3"

disableKinds:
- taxonomy
- taxonomyTerm
- sitemap

mediaTypes:
  application/yaml:
    suffixes: ["yml"]

outputFormats:
  YAML:
    mediaType: "application/yaml"
    isPlainText: true

outputs:
  page:
  - HTML
  - JSON
  - YAML

params:
  BookShowToC: true
  BookMenuBundle: "/_menu"
